/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ariel
 */
public class Pagamento_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento_GUI
     */
    public Pagamento_GUI() {
        initComponents();
        Panel_Credit_PNL.setVisible(false);
        Panel_PIX_PNL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentMethods = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        Banner_IMG = new org.edisoncor.gui.panel.PanelImage();
        Close_BTN = new javax.swing.JButton();
        Name_LBL = new javax.swing.JLabel();
        Nome_TXF = new javax.swing.JTextField();
        Contact_LBL = new javax.swing.JLabel();
        Contact_JTF = new javax.swing.JTextField();
        CPF_LBL = new javax.swing.JLabel();
        CPF_TXF = new javax.swing.JTextField();
        Info_LBL = new javax.swing.JLabel();
        InfoPayment_LBL = new javax.swing.JLabel();
        Methods_PNL = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Panel_PIX_PNL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        Panel_Credit_PNL = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Effect_Payment_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(102, 102, 102));
        Background.setLayout(null);

        Banner_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MK Label.png"))); // NOI18N

        javax.swing.GroupLayout Banner_IMGLayout = new javax.swing.GroupLayout(Banner_IMG);
        Banner_IMG.setLayout(Banner_IMGLayout);
        Banner_IMGLayout.setHorizontalGroup(
            Banner_IMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        Banner_IMGLayout.setVerticalGroup(
            Banner_IMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Background.add(Banner_IMG);
        Banner_IMG.setBounds(10, 0, 480, 110);

        Close_BTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Close_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Close_BTN.setText("X");
        Close_BTN.setBorderPainted(false);
        Close_BTN.setContentAreaFilled(false);
        Close_BTN.setFocusable(false);
        Close_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_BTNActionPerformed(evt);
            }
        });
        Background.add(Close_BTN);
        Close_BTN.setBounds(490, 10, 50, 30);

        Name_LBL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Name_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Name_LBL.setText("Nome");
        Background.add(Name_LBL);
        Name_LBL.setBounds(30, 170, 200, 30);

        Nome_TXF.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Background.add(Nome_TXF);
        Nome_TXF.setBounds(30, 200, 200, 30);

        Contact_LBL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Contact_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Contact_LBL.setText("Contato");
        Background.add(Contact_LBL);
        Contact_LBL.setBounds(30, 270, 200, 30);

        Contact_JTF.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Background.add(Contact_JTF);
        Contact_JTF.setBounds(30, 300, 200, 30);

        CPF_LBL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CPF_LBL.setForeground(new java.awt.Color(255, 255, 255));
        CPF_LBL.setText("CPF");
        Background.add(CPF_LBL);
        CPF_LBL.setBounds(30, 360, 200, 30);

        CPF_TXF.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Background.add(CPF_TXF);
        CPF_TXF.setBounds(30, 390, 200, 30);

        Info_LBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Info_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Info_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Info_LBL.setText("Informações de Cadastro");
        Background.add(Info_LBL);
        Info_LBL.setBounds(20, 140, 230, 22);

        InfoPayment_LBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        InfoPayment_LBL.setForeground(new java.awt.Color(255, 255, 255));
        InfoPayment_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoPayment_LBL.setText("Informações de Pagamento");
        Background.add(InfoPayment_LBL);
        InfoPayment_LBL.setBounds(260, 140, 260, 22);

        Methods_PNL.setBackground(new java.awt.Color(153, 153, 153));
        Methods_PNL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Métodos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        PaymentMethods.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jRadioButton1.setText("Cartão de Crédito");

        PaymentMethods.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jRadioButton2.setText("PIX");

        javax.swing.GroupLayout Methods_PNLLayout = new javax.swing.GroupLayout(Methods_PNL);
        Methods_PNL.setLayout(Methods_PNLLayout);
        Methods_PNLLayout.setHorizontalGroup(
            Methods_PNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Methods_PNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        Methods_PNLLayout.setVerticalGroup(
            Methods_PNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Methods_PNLLayout.createSequentialGroup()
                .addGroup(Methods_PNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        Background.add(Methods_PNL);
        Methods_PNL.setBounds(270, 170, 240, 50);

        Panel_PIX_PNL.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Panel_PIX_PNL.add(jScrollPane1);
        jScrollPane1.setBounds(10, 26, 130, 110);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Chave PIX");
        Panel_PIX_PNL.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 14);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QR Code.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Panel_PIX_PNL.add(panelImage1);
        panelImage1.setBounds(150, 50, 80, 80);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Código QR");
        Panel_PIX_PNL.add(jLabel2);
        jLabel2.setBounds(150, 30, 80, 14);

        Background.add(Panel_PIX_PNL);
        Panel_PIX_PNL.setBounds(270, 230, 240, 150);

        Panel_Credit_PNL.setLayout(null);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Panel_Credit_PNL.add(jTextField4);
        jTextField4.setBounds(10, 31, 220, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Número do Cartão");
        Panel_Credit_PNL.add(jLabel6);
        jLabel6.setBounds(10, 11, 87, 14);

        jTextField5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Panel_Credit_PNL.add(jTextField5);
        jTextField5.setBounds(10, 77, 220, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Nome do(a) Titular");
        Panel_Credit_PNL.add(jLabel7);
        jLabel7.setBounds(10, 57, 88, 14);

        jTextField6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Panel_Credit_PNL.add(jTextField6);
        jTextField6.setBounds(10, 123, 80, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("CVV");
        Panel_Credit_PNL.add(jLabel8);
        jLabel8.setBounds(10, 103, 50, 14);

        jTextField7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Panel_Credit_PNL.add(jTextField7);
        jTextField7.setBounds(100, 123, 130, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Data de Vencimento");
        Panel_Credit_PNL.add(jLabel9);
        jLabel9.setBounds(103, 103, 130, 14);

        Background.add(Panel_Credit_PNL);
        Panel_Credit_PNL.setBounds(270, 230, 240, 150);

        Effect_Payment_BTN.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Effect_Payment_BTN.setText("Efetuar Pagamento");
        Background.add(Effect_Payment_BTN);
        Effect_Payment_BTN.setBounds(270, 390, 240, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(539, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Close_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamento_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private org.edisoncor.gui.panel.PanelImage Banner_IMG;
    private javax.swing.JLabel CPF_LBL;
    private javax.swing.JTextField CPF_TXF;
    private javax.swing.JButton Close_BTN;
    private javax.swing.JTextField Contact_JTF;
    private javax.swing.JLabel Contact_LBL;
    private javax.swing.JButton Effect_Payment_BTN;
    private javax.swing.JLabel InfoPayment_LBL;
    private javax.swing.JLabel Info_LBL;
    private javax.swing.JPanel Methods_PNL;
    private javax.swing.JLabel Name_LBL;
    private javax.swing.JTextField Nome_TXF;
    private javax.swing.JPanel Panel_Credit_PNL;
    private javax.swing.JPanel Panel_PIX_PNL;
    private javax.swing.ButtonGroup PaymentMethods;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
