/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ariel
 */
public class Pedido_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pedido_GUI
     */
    public Pedido_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Banner_IMG = new org.edisoncor.gui.panel.PanelImage();
        Classic_LBL = new javax.swing.JLabel();
        Classic_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Cheddarcon_LBL = new javax.swing.JLabel();
        Cheddarcon_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Doubleef_LBL = new javax.swing.JLabel();
        Doubleef_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Vegano_LBL = new javax.swing.JLabel();
        Vegano_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Crook_LBL = new javax.swing.JLabel();
        Crook_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Tower_LBL = new javax.swing.JLabel();
        Tower_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Cola_LBL = new javax.swing.JLabel();
        Cola_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Juice_LBL = new javax.swing.JLabel();
        Juice_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Lanches_LBL = new javax.swing.JLabel();
        Bebidas_LBL = new javax.swing.JLabel();
        Extras_LBL = new javax.swing.JLabel();
        Close_BTN = new javax.swing.JButton();
        Fries_LBL = new javax.swing.JLabel();
        Fries_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Chicken_LBL = new javax.swing.JLabel();
        Chicken_IMG = new org.edisoncor.gui.button.ButtonIcon();
        Tower_QNT = new javax.swing.JLabel();
        Classic_QNT = new javax.swing.JLabel();
        Vegano_QNT = new javax.swing.JLabel();
        Cola_QNT = new javax.swing.JLabel();
        Fries_QNT = new javax.swing.JLabel();
        Chicken_QNT = new javax.swing.JLabel();
        Juice_QNT = new javax.swing.JLabel();
        Crook_QNT = new javax.swing.JLabel();
        Cheddarcon_QNT = new javax.swing.JLabel();
        Doubleef_QNT = new javax.swing.JLabel();
        Effect_BTN = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(102, 102, 102));
        Background.setLayout(null);

        Banner_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MK Label.png"))); // NOI18N

        javax.swing.GroupLayout Banner_IMGLayout = new javax.swing.GroupLayout(Banner_IMG);
        Banner_IMG.setLayout(Banner_IMGLayout);
        Banner_IMGLayout.setHorizontalGroup(
            Banner_IMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        Banner_IMGLayout.setVerticalGroup(
            Banner_IMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Background.add(Banner_IMG);
        Banner_IMG.setBounds(10, 0, 480, 110);

        Classic_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Classic_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Classic_LBL.setText("Clássico R$ 10.50");
        Background.add(Classic_LBL);
        Classic_LBL.setBounds(20, 150, 100, 14);

        Classic_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Classico.png"))); // NOI18N
        Classic_IMG.setText("buttonIcon1");
        Background.add(Classic_IMG);
        Classic_IMG.setBounds(20, 170, 70, 60);

        Cheddarcon_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cheddarcon_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Cheddarcon_LBL.setText("Cheddarcon R$ 15.50");
        Background.add(Cheddarcon_LBL);
        Cheddarcon_LBL.setBounds(20, 260, 110, 14);

        Cheddarcon_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bacon c Cheddar.png"))); // NOI18N
        Cheddarcon_IMG.setText("buttonIcon1");
        Background.add(Cheddarcon_IMG);
        Cheddarcon_IMG.setBounds(20, 280, 70, 60);

        Doubleef_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Doubleef_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Doubleef_LBL.setText("Doubleef R$ 18.50");
        Background.add(Doubleef_LBL);
        Doubleef_LBL.setBounds(20, 370, 100, 14);

        Doubleef_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Duas Carnes.png"))); // NOI18N
        Doubleef_IMG.setText("buttonIcon1");
        Background.add(Doubleef_IMG);
        Doubleef_IMG.setBounds(20, 390, 70, 60);

        Vegano_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Vegano_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Vegano_LBL.setText("Vegano R$ 20.00");
        Background.add(Vegano_LBL);
        Vegano_LBL.setBounds(140, 150, 90, 14);

        Vegano_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Vegano.png"))); // NOI18N
        Vegano_IMG.setText("buttonIcon1");
        Background.add(Vegano_IMG);
        Vegano_IMG.setBounds(140, 170, 70, 60);

        Crook_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Crook_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Crook_LBL.setText("Crook R$ 17.30");
        Background.add(Crook_LBL);
        Crook_LBL.setBounds(140, 260, 100, 14);

        Crook_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Recheado.png"))); // NOI18N
        Crook_IMG.setText("buttonIcon1");
        Background.add(Crook_IMG);
        Crook_IMG.setBounds(140, 280, 70, 60);

        Tower_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Tower_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Tower_LBL.setText("Tower R$ 25.00");
        Background.add(Tower_LBL);
        Tower_LBL.setBounds(140, 370, 90, 14);

        Tower_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tower.png"))); // NOI18N
        Tower_IMG.setText("buttonIcon1");
        Background.add(Tower_IMG);
        Tower_IMG.setBounds(140, 390, 70, 60);

        Cola_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cola_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Cola_LBL.setText("Coca-Cola 750ml R$ 5.00");
        Background.add(Cola_LBL);
        Cola_LBL.setBounds(250, 150, 130, 14);

        Cola_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CocaCola.png"))); // NOI18N
        Cola_IMG.setText("buttonIcon1");
        Background.add(Cola_IMG);
        Cola_IMG.setBounds(250, 170, 70, 60);

        Juice_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Juice_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Juice_LBL.setText("Suco Natural 500ml R$ 3.50");
        Background.add(Juice_LBL);
        Juice_LBL.setBounds(250, 260, 140, 14);

        Juice_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Suco.png"))); // NOI18N
        Juice_IMG.setText("buttonIcon1");
        Background.add(Juice_IMG);
        Juice_IMG.setBounds(250, 280, 70, 60);

        Lanches_LBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lanches_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Lanches_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lanches_LBL.setText("Lanches");
        Background.add(Lanches_LBL);
        Lanches_LBL.setBounds(20, 120, 190, 22);

        Bebidas_LBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Bebidas_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Bebidas_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bebidas_LBL.setText("Bebidas");
        Background.add(Bebidas_LBL);
        Bebidas_LBL.setBounds(240, 120, 90, 22);

        Extras_LBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Extras_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Extras_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Extras_LBL.setText("Extras");
        Background.add(Extras_LBL);
        Extras_LBL.setBounds(380, 120, 90, 22);

        Close_BTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Close_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Close_BTN.setText("X");
        Close_BTN.setBorderPainted(false);
        Close_BTN.setContentAreaFilled(false);
        Close_BTN.setFocusable(false);
        Close_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_BTNActionPerformed(evt);
            }
        });
        Background.add(Close_BTN);
        Close_BTN.setBounds(490, 10, 50, 30);

        Fries_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Fries_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Fries_LBL.setText("Batata-Frita 250g R$ 5.00");
        Background.add(Fries_LBL);
        Fries_LBL.setBounds(390, 150, 140, 14);

        Fries_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BatataFrita.png"))); // NOI18N
        Fries_IMG.setText("buttonIcon1");
        Background.add(Fries_IMG);
        Fries_IMG.setBounds(390, 170, 70, 60);

        Chicken_LBL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Chicken_LBL.setForeground(new java.awt.Color(255, 255, 255));
        Chicken_LBL.setText("Nuggets 250g R$ 6.50");
        Background.add(Chicken_LBL);
        Chicken_LBL.setBounds(390, 260, 130, 14);

        Chicken_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Nuggets.png"))); // NOI18N
        Chicken_IMG.setText("buttonIcon1");
        Background.add(Chicken_IMG);
        Chicken_IMG.setBounds(390, 280, 70, 60);

        Tower_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Tower_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tower_QNT.setText("0");
        Background.add(Tower_QNT);
        Tower_QNT.setBounds(140, 450, 70, 30);

        Classic_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Classic_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Classic_QNT.setText("0");
        Background.add(Classic_QNT);
        Classic_QNT.setBounds(20, 230, 70, 30);

        Vegano_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Vegano_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vegano_QNT.setText("0");
        Background.add(Vegano_QNT);
        Vegano_QNT.setBounds(140, 230, 70, 30);

        Cola_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cola_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cola_QNT.setText("0");
        Background.add(Cola_QNT);
        Cola_QNT.setBounds(250, 230, 70, 30);

        Fries_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Fries_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fries_QNT.setText("0");
        Background.add(Fries_QNT);
        Fries_QNT.setBounds(390, 230, 70, 30);

        Chicken_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Chicken_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken_QNT.setText("0");
        Background.add(Chicken_QNT);
        Chicken_QNT.setBounds(390, 340, 70, 30);

        Juice_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Juice_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Juice_QNT.setText("0");
        Background.add(Juice_QNT);
        Juice_QNT.setBounds(250, 340, 70, 30);

        Crook_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Crook_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Crook_QNT.setText("0");
        Background.add(Crook_QNT);
        Crook_QNT.setBounds(140, 340, 70, 30);

        Cheddarcon_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cheddarcon_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cheddarcon_QNT.setText("0");
        Background.add(Cheddarcon_QNT);
        Cheddarcon_QNT.setBounds(20, 340, 70, 30);

        Doubleef_QNT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Doubleef_QNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Doubleef_QNT.setText("0");
        Background.add(Doubleef_QNT);
        Doubleef_QNT.setBounds(20, 450, 70, 30);

        Effect_BTN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Effect_BTN.setText("Efetuar Pedido");
        Effect_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Effect_BTNActionPerformed(evt);
            }
        });
        Background.add(Effect_BTN);
        Effect_BTN.setBounds(290, 430, 150, 40);

        jTextField1.setEditable(false);
        jTextField1.setText("R$ 0.00");
        Background.add(jTextField1);
        jTextField1.setBounds(290, 400, 150, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valor Total");
        Background.add(jLabel1);
        jLabel1.setBounds(290, 380, 150, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(539, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Close_BTNActionPerformed

    private void Effect_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Effect_BTNActionPerformed
        new Pagamento_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Effect_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private org.edisoncor.gui.panel.PanelImage Banner_IMG;
    private javax.swing.JLabel Bebidas_LBL;
    private org.edisoncor.gui.button.ButtonIcon Cheddarcon_IMG;
    private javax.swing.JLabel Cheddarcon_LBL;
    public static javax.swing.JLabel Cheddarcon_QNT;
    private org.edisoncor.gui.button.ButtonIcon Chicken_IMG;
    private javax.swing.JLabel Chicken_LBL;
    public static javax.swing.JLabel Chicken_QNT;
    private org.edisoncor.gui.button.ButtonIcon Classic_IMG;
    private javax.swing.JLabel Classic_LBL;
    public static javax.swing.JLabel Classic_QNT;
    private javax.swing.JButton Close_BTN;
    private org.edisoncor.gui.button.ButtonIcon Cola_IMG;
    private javax.swing.JLabel Cola_LBL;
    public static javax.swing.JLabel Cola_QNT;
    private org.edisoncor.gui.button.ButtonIcon Crook_IMG;
    private javax.swing.JLabel Crook_LBL;
    public static javax.swing.JLabel Crook_QNT;
    private org.edisoncor.gui.button.ButtonIcon Doubleef_IMG;
    private javax.swing.JLabel Doubleef_LBL;
    public static javax.swing.JLabel Doubleef_QNT;
    private javax.swing.JButton Effect_BTN;
    private javax.swing.JLabel Extras_LBL;
    private org.edisoncor.gui.button.ButtonIcon Fries_IMG;
    private javax.swing.JLabel Fries_LBL;
    public static javax.swing.JLabel Fries_QNT;
    private org.edisoncor.gui.button.ButtonIcon Juice_IMG;
    private javax.swing.JLabel Juice_LBL;
    public static javax.swing.JLabel Juice_QNT;
    private javax.swing.JLabel Lanches_LBL;
    private org.edisoncor.gui.button.ButtonIcon Tower_IMG;
    private javax.swing.JLabel Tower_LBL;
    public static javax.swing.JLabel Tower_QNT;
    private org.edisoncor.gui.button.ButtonIcon Vegano_IMG;
    private javax.swing.JLabel Vegano_LBL;
    public static javax.swing.JLabel Vegano_QNT;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
