/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ariel
 */
public class Pedido_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pedido_GUI
     */
    public Pedido_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonIcon2 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel3 = new javax.swing.JLabel();
        buttonIcon3 = new org.edisoncor.gui.button.ButtonIcon();
        buttonIcon4 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel4 = new javax.swing.JLabel();
        buttonIcon5 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonIcon6 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel7 = new javax.swing.JLabel();
        buttonIcon7 = new org.edisoncor.gui.button.ButtonIcon();
        buttonIcon8 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonIcon10 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel14 = new javax.swing.JLabel();
        buttonIcon11 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fundo.setBackground(new java.awt.Color(102, 102, 102));
        Fundo.setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MK Label.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Fundo.add(panelImage2);
        panelImage2.setBounds(10, 0, 480, 110);

        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Classico.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");
        Fundo.add(buttonIcon1);
        buttonIcon1.setBounds(20, 170, 70, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clássico R$ 10.50");
        Fundo.add(jLabel1);
        jLabel1.setBounds(20, 150, 100, 14);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cheddarcon R$ 15.50");
        Fundo.add(jLabel2);
        jLabel2.setBounds(20, 260, 110, 14);

        buttonIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bacon c Cheddar.png"))); // NOI18N
        buttonIcon2.setText("buttonIcon1");
        Fundo.add(buttonIcon2);
        buttonIcon2.setBounds(20, 280, 70, 60);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doubleef R$ 18.50");
        Fundo.add(jLabel3);
        jLabel3.setBounds(20, 370, 100, 14);

        buttonIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Duas Carnes.png"))); // NOI18N
        buttonIcon3.setText("buttonIcon1");
        Fundo.add(buttonIcon3);
        buttonIcon3.setBounds(20, 390, 70, 60);

        buttonIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Vegano.png"))); // NOI18N
        buttonIcon4.setText("buttonIcon1");
        Fundo.add(buttonIcon4);
        buttonIcon4.setBounds(140, 170, 70, 60);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vegano R$ 20.00");
        Fundo.add(jLabel4);
        jLabel4.setBounds(140, 150, 90, 14);

        buttonIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Recheado.png"))); // NOI18N
        buttonIcon5.setText("buttonIcon1");
        Fundo.add(buttonIcon5);
        buttonIcon5.setBounds(140, 280, 70, 60);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Crook R$ 17.30");
        Fundo.add(jLabel5);
        jLabel5.setBounds(140, 260, 100, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tower R$ 25.00");
        Fundo.add(jLabel6);
        jLabel6.setBounds(140, 370, 90, 14);

        buttonIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tower.png"))); // NOI18N
        buttonIcon6.setText("buttonIcon1");
        Fundo.add(buttonIcon6);
        buttonIcon6.setBounds(140, 390, 70, 60);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coca-Cola 750ml R$ 5.00");
        Fundo.add(jLabel7);
        jLabel7.setBounds(250, 150, 130, 14);

        buttonIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CocaCola.png"))); // NOI18N
        buttonIcon7.setText("buttonIcon1");
        Fundo.add(buttonIcon7);
        buttonIcon7.setBounds(250, 170, 70, 60);

        buttonIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Suco.png"))); // NOI18N
        buttonIcon8.setText("buttonIcon1");
        Fundo.add(buttonIcon8);
        buttonIcon8.setBounds(250, 280, 70, 60);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Suco Natural 500ml R$ 3.50");
        Fundo.add(jLabel8);
        jLabel8.setBounds(250, 260, 140, 14);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bebidas");
        Fundo.add(jLabel10);
        jLabel10.setBounds(240, 120, 90, 22);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Lanches");
        Fundo.add(jLabel11);
        jLabel11.setBounds(20, 120, 190, 22);

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Fundo.add(jButton3);
        jButton3.setBounds(490, 10, 50, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Extras");
        Fundo.add(jLabel12);
        jLabel12.setBounds(380, 120, 90, 22);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Batata-Frita 250g R$ 5.00");
        Fundo.add(jLabel13);
        jLabel13.setBounds(390, 150, 140, 14);

        buttonIcon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BatataFrita.png"))); // NOI18N
        buttonIcon10.setText("buttonIcon1");
        Fundo.add(buttonIcon10);
        buttonIcon10.setBounds(390, 170, 70, 60);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nuggets 250g R$ 6.50");
        Fundo.add(jLabel14);
        jLabel14.setBounds(390, 260, 130, 14);

        buttonIcon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Nuggets.png"))); // NOI18N
        buttonIcon11.setText("buttonIcon1");
        Fundo.add(buttonIcon11);
        buttonIcon11.setBounds(390, 280, 70, 60);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0");
        Fundo.add(jLabel9);
        jLabel9.setBounds(140, 450, 70, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0");
        Fundo.add(jLabel15);
        jLabel15.setBounds(20, 230, 70, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("0");
        Fundo.add(jLabel16);
        jLabel16.setBounds(140, 230, 70, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("0");
        Fundo.add(jLabel17);
        jLabel17.setBounds(250, 230, 70, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        Fundo.add(jLabel18);
        jLabel18.setBounds(390, 230, 70, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");
        Fundo.add(jLabel19);
        jLabel19.setBounds(390, 340, 70, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("0");
        Fundo.add(jLabel20);
        jLabel20.setBounds(250, 340, 70, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("0");
        Fundo.add(jLabel21);
        jLabel21.setBounds(140, 340, 70, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0");
        Fundo.add(jLabel22);
        jLabel22.setBounds(20, 340, 70, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("0");
        Fundo.add(jLabel23);
        jLabel23.setBounds(20, 450, 70, 30);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Fechar Pedido");
        Fundo.add(jButton4);
        jButton4.setBounds(290, 400, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(539, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fundo;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon10;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon11;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon2;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon3;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon4;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon5;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon6;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon7;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
